import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import {categories,processes,Process} from './data';

const Logo=({compact=false}:{compact?:boolean})=><div className={compact?'brand compact':'brand'}><img src="/assets/prepora-symbol.png"/><span>PREPORA</span></div>;
const AlphaAttribution=()=> <div className="alpha-attribution"><span>A product by</span><img src="/assets/alpha-primary.png" alt="ALPHA"/></div>;

function App(){
 const [query,setQuery]=useState(''); const [category,setCategory]=useState<string|null>(null); const [selected,setSelected]=useState<Process|null>(null); const [done,setDone]=useState<Record<string,boolean>>({});
 const visible=useMemo(()=>processes.filter(p=>(!category||p.category===category)&&(!query||`${p.title} ${p.category}`.toLowerCase().includes(query.toLowerCase()))),[category,query]);
 const open=(p:Process)=>{setSelected(p);setDone({});window.scrollTo({top:0,behavior:'smooth'})};
 if(selected) return <main><header className="topbar"><button className="back" onClick={()=>setSelected(null)}>← Back</button><Logo compact/><div className="topcount">{selected.category}</div></header><section className="detail"><div className="eyebrow">{selected.category}</div><h1>{selected.title}</h1><p className="lead">{selected.description}</p><div className="trust"><b>Preparation guide</b><span>Requirements may change. Verify important details on the official source before submitting.</span></div><div className="grid"><Panel title="Before you start" items={selected.eligibility}/><Panel title="Documents you may need" items={selected.documents}/><Panel title="Information to keep ready" items={selected.information}/><div className="card"><h2>Quick facts</h2><p><b>Mode:</b> {selected.mode}</p><p><b>Fees:</b> {selected.fees}</p><p><b>Typical time:</b> {selected.time}</p></div></div><div className="card"><h2>What to do</h2><ol className="steps">{selected.steps.map((s,i)=><li key={i}><span>{i+1}</span>{s}</li>)}</ol></div><div className="card"><h2>Checklist</h2><div className="checks">{selected.checklist.map((s,i)=><label key={i} className={done[i]?'checked':''}><input type="checkbox" checked={!!done[i]} onChange={e=>setDone({...done,[i]:e.target.checked})}/><span>{s}</span></label>)}</div><div className="ready">{Object.values(done).filter(Boolean).length}/{selected.checklist.length} ready</div></div><div className="grid"><Panel title="Important" items={selected.important}/><Panel title="Common mistakes" items={selected.mistakes}/></div><div className="source"><div><b>Source</b><p>{selected.source}</p><small>{selected.lastVerified}</small></div><a href={selected.sourceUrl} target="_blank" rel="noreferrer">Open source ↗</a></div><footer><AlphaAttribution/></footer></section></main>;
 return <main><header className="topbar"><Logo compact/><div className="topcount">{processes.length}+ processes</div></header><section className="hero"><div className="hero-logo"><img src="/assets/prepora-primary.png"/></div><div className="eyebrow">PREPARATION INTELLIGENCE</div><h1>Know what you need<br/>before you begin.</h1><p>PREPORA turns confusing real-world processes into clear preparation steps, requirements and checklists.</p><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="What are you preparing for?"/></div></section><section className="content"><div className="section-head"><div><div className="eyebrow">EXPLORE</div><h2>What are you preparing for?</h2></div><span>{visible.length} results</span></div><div className="chips">{categories.map(c=><button className={category===c?'active':''} onClick={()=>setCategory(category===c?null:c)} key={c}>{c}</button>)}</div><div className="process-grid">{visible.map(p=><button className="process-card" key={p.id} onClick={()=>open(p)}><span className="mini">{p.category}</span><h3>{p.title}</h3><p>{p.description}</p><span className="arrow">→</span></button>)}</div>{!visible.length&&<div className="empty">No process found. Try another keyword or category.</div>}<footer><AlphaAttribution/></footer></section></main>}
const Panel=({title,items}:{title:string;items:string[]})=><div className="card"><h2>{title}</h2><ul>{items.map((x,i)=><li key={i}>{x}</li>)}</ul></div>;
createRoot(document.getElementById('root')!).render(<App/>);
